sudo: required
dist: trusty

git:
  depth: 3

language: scala
scala: 2.13.3

jdk:
  - openjdk11

before_install:
 - sudo apt-get update -q

script:
 - sbt '+ compile'
 - sbt 'Test/compile'
 - sbt doc
